name:Postman Collection Workflow
on:
  push:
    branches : [main]
  workflow-dispatch:
  schedule:
    - cron : '30 02 * * *' #8AM IST
    - cron : '00 14 * * *'  #7:30 PM IST
    - cron : '00 06 * * 1-5'  #7:30 PM IST

jobs:
  run-postman-tests:
    runs-on : ubuntu-latest

    steps:
      - name : Checkout the code
        uses: actions/checkout@v5.0.0

     - name : Install node.js and npm
       uses : actions/setup-node@v3.9.1
       with : 
         node-versions : '22'

    - name : Install newman and HTML-extra globally
      run : |
            npm install -g newman
            npm install -g newman-reporter-htmlextra

   - name : Run the postman collection with newman
     run : |
           newman run 'Inwarranty-flow Collection Copy.postman_collection.json' \
           -e QA.postman_environment.json \
           - d testdata.csv \
           -r cli,htmlextra
        
      
    
  
    
